### ISSUE TITLE
Suggestion: Drop support for Python 3.6

### ISSUE THREAD

**Issue by aqeelat** [philgyford/django-spectator#83]
Since 3.6 reached EOL a while ago, it might be time to drop support for it. I can take on this task.

**Comment by aqeelat** [comment]
@philgyford I added https://github.com/asottile/pyupgrade to the pre-commit config locally and ran it against the repo. Do you want me to keep it and include it in the PR?

**Comment by philgyford** [comment]
Sorry for the slow reply. I don't _think_ I'd want it in there, if it's done the job already? Unless you have a good reason why :) I'm not familiar with it. Thanks.

**Comment by aqeelat** [comment]
@philgyford it will check future PRs. But that's a another discussion. I'll open my PR soon.
